### ISSUE TITLE
Android API not working (edited from Working with Angular 2)

### ISSUE THREAD

**Issue by jiwonyune** [TheOriginalJosh/nativescript-image-colors#1]
Hi,

Can anyone help me get it working with Angular 2?

Also, the demo app itself is not working at all. Maybe there is a problem with versions.

Thanks a lot in advance.

**Comment by jiwonyune** [comment]
I figured out that the problem is not with Angular 2, but with Android API. I keep getting an error `... getDrawable is not a function`. Can anyone look into the Android side, if anything has changed from the original?

**Comment by JoshDSommer** [comment]
@jiwonyune I know this is really old, sorry for the delay. but I've fixed the issue that caused this. Basically image colors were firing before the image was loaded so there was nothing to get colors from. Now if this happens it just returns the color black for all the colors. Thank you for reporting this.
